# Generated by Django 4.0.3 on 2022-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='education',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='myuser',
            name='therapy_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
